services:
  ping-pong-frontend:
    container_name: ping-pong-frontend
    image: ping-pong-frontend
    build:
      context: ./ping-pong-frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    hostname: ping-pong-frontend
    ports:
      - 3000:3000

  backend:
    container_name: backend
    image: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    hostname: backend
    ports:
      - 8082:8082
    links:
      - auth:auth
      - game-service:game-service
    depends_on:
      - auth
      - game-service


  game-service:
    container_name: game-service
    image: game-service
    build:
      context: ./game-service
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    hostname: game-service
    ports:
      - 8081:8081
  nginx:
    container_name: reverse-proxy-nginx
    image: reverse-proxy-nginx
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    hostname: nginx
    ports:
      # - 80:80
      - 8443:443
    links:
      - ping-pong-frontend:ping-pong-frontend
      - backend:backend
      - gateway:gateway
    depends_on:
      - ping-pong-frontend
      - backend
      - gateway


  auth:
    container_name: auth
    image: auth
    build:
      context: ./auth
    volumes:
      - db:/db
    ports:
      - 8083:8083

  score:
    container_name: score
    image: score
    build:
      context: ./score
    volumes:
      - db:/db
    ports:
      - 8084:8084

  gateway:
    container_name: gateway
    image: gateway
    build:
      context: ./gateway
    volumes:
      - db:/db
    ports:
      - 8085:8085
    links:
      - auth:auth
      - score:score
    depends_on:
      - auth
      - score

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: C:\Projects\_mariadb_volume
      device: /home/chustei/sgoinfre/_mariadb_volume

